name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crytic/slither-action@v0.4.0
        with:
          fail-on: high
          slither-args: "--exclude lib/solmate/src/,lib/solady/src/,lib/ds-test/src/,lib/splits-utils/test/"
